// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRRv03hL2sGgJz87DUmGXH7kW4J2IPk4',
    appId: '1:995891524004:web:5e739a64b0f7c90c7e1131',
    messagingSenderId: '995891524004',
    projectId: 'prj-pab-si61-2327240031',
    authDomain: 'prj-pab-si61-2327240031.firebaseapp.com',
    storageBucket: 'prj-pab-si61-2327240031.firebasestorage.app',
    measurementId: 'G-MVJVDLE9KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNV7eu57vk_ROKZ3-J6RyBmwqRkITX3d8',
    appId: '1:995891524004:android:bf53fe05270f1afe7e1131',
    messagingSenderId: '995891524004',
    projectId: 'prj-pab-si61-2327240031',
    storageBucket: 'prj-pab-si61-2327240031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqqW6cqBXPJ9c7DzG5VDGrhW6UPrXPWE',
    appId: '1:995891524004:ios:394b74aa988be7f57e1131',
    messagingSenderId: '995891524004',
    projectId: 'prj-pab-si61-2327240031',
    storageBucket: 'prj-pab-si61-2327240031.firebasestorage.app',
    iosClientId: '995891524004-a5p0tutp9ortr1ivuk19jrmk3s4lpljn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxqqW6cqBXPJ9c7DzG5VDGrhW6UPrXPWE',
    appId: '1:995891524004:ios:394b74aa988be7f57e1131',
    messagingSenderId: '995891524004',
    projectId: 'prj-pab-si61-2327240031',
    storageBucket: 'prj-pab-si61-2327240031.firebasestorage.app',
    iosClientId: '995891524004-a5p0tutp9ortr1ivuk19jrmk3s4lpljn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfRRv03hL2sGgJz87DUmGXH7kW4J2IPk4',
    appId: '1:995891524004:web:831db48befda05bf7e1131',
    messagingSenderId: '995891524004',
    projectId: 'prj-pab-si61-2327240031',
    authDomain: 'prj-pab-si61-2327240031.firebaseapp.com',
    storageBucket: 'prj-pab-si61-2327240031.firebasestorage.app',
    measurementId: 'G-F8DY69ZXJJ',
  );
}
